# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Add_Sets_Layers
                                 A QGIS plugin
 Add Sets of Layers for facilily consolidation of potential map
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-14
        copyright            : (C) 2026 by Code4Construct
        email                : ubonira@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Add_Sets_Layers class from file Add_Sets_Layers.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .add_sets_layers import Add_Sets_Layers
    return Add_Sets_Layers(iface)
