# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WardBoundaryBuffer
                                 A QGIS plugin
 This plugin draws a ward boundary buffer from a selected feature, and saves the feature as a star marker.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-15
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Code4Construst
        email                : ubonira@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox
from qgis.core import QgsMapLayer, QgsPointXY, QgsProject, QgsWkbTypes
from qgis.gui import QgsMapToolIdentify

# Initialize Qt resources from file resources.py
from .resources import *
import os.path
from . import ward_boundary_buffer_frame as WBBF


class PointPickAndRunMapTool(QgsMapToolIdentify):
    def __init__(self, iface, run_callback, previous_tool=None, center_mode='point_feature'):
        super().__init__(iface.mapCanvas())
        self.iface = iface
        self.run_callback = run_callback
        self.previous_tool = previous_tool
        self.center_mode = center_mode
        self.setCursor(Qt.CrossCursor)

    def canvasReleaseEvent(self, event):
        if self.center_mode == 'map_coordinate':
            point = self.toMapCoordinates(event.pos())
            WBBF.create_selected_center_point_layer(self.iface, QgsPointXY(point))
            self._restore_previous_tool()
            self._run_callback()
            return

        results = self.identify(event.x(), event.y(), self.TopDownAll, self.VectorLayer)
        for result in results:
            layer = result.mLayer
            if not self._is_point_layer(layer):
                continue
            feature = result.mFeature
            self._select_point(layer, feature.id())
            self._restore_previous_tool()
            self._run_callback()
            return

        QMessageBox.information(
            self.iface.mainWindow(),
            '区境界・バッファを作成',
            'クリックした位置にポイント地物が見つかりませんでした。ポイントをクリックしてください。',
        )

    def _is_point_layer(self, layer):
        if layer is None or layer.type() != QgsMapLayer.VectorLayer:
            return False
        return QgsWkbTypes.geometryType(layer.wkbType()) == QgsWkbTypes.PointGeometry

    def _select_point(self, target_layer, feature_id):
        for layer in QgsProject.instance().mapLayers().values():
            if self._is_point_layer(layer):
                layer.removeSelection()
        self.iface.setActiveLayer(target_layer)
        target_layer.selectByIds([feature_id])
        self.iface.mapCanvas().refresh()

    def _restore_previous_tool(self):
        if self.previous_tool is not None:
            self.canvas().setMapTool(self.previous_tool)

    def _run_callback(self):
        try:
            self.run_callback()
        except Exception as exc:
            QMessageBox.critical(
                self.iface.mainWindow(),
                '区境界・バッファを作成',
                str(exc),
            )


class WardBoundaryBuffer:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'WardBoundaryBuffer_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Ward Boundary Buffer')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        self.point_pick_tool = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('WardBoundaryBuffer', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(self.plugin_dir, 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'Ward Boundary Buffer'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Ward Boundary Buffer'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""
        try:
            settings = WBBF.collect_ward_boundary_buffer_output_settings(self.iface)
        except WBBF.WardBoundaryBufferSettingsCancelled:
            return
        except Exception as exc:
            QMessageBox.critical(
                self.iface.mainWindow(),
                self.tr(u'区境界・バッファを作成'),
                str(exc),
            )
            return

        canvas = self.iface.mapCanvas()
        self.point_pick_tool = PointPickAndRunMapTool(
            self.iface,
            lambda: WBBF.run_ward_boundary_buffer(iface=self.iface, settings=settings),
            canvas.mapTool(),
            settings.get('center_mode', 'point_feature'),
        )
        canvas.setMapTool(self.point_pick_tool)
        instruction = (
            self.tr(u'地図上のポイントをクリックしてください。クリックしたポイントのレイヤと地物を自動選択して処理を開始します。')
            if settings.get('center_mode') == 'point_feature'
            else self.tr(u'円の中心にしたい位置を地図上でクリックしてください。その座標から処理を開始します。')
        )
        QMessageBox.information(
            self.iface.mainWindow(),
            self.tr(u'区境界・バッファを作成'),
            instruction,
        )
