# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MergeFeaturesInPolygon
                                 A QGIS plugin
 ポリゴン内の地物抽出
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-29
        copyright            : (C) 2026 by code4construct
        email                : ubonira@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MergeFeaturesInPolygon class from file MergeFeaturesInPolygon.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .merge_features_in_polygon import MergeFeaturesInPolygon
    return MergeFeaturesInPolygon(iface)
